### ISSUE TITLE
Fails on e300, works on e1000

### ISSUE THREAD

**Issue by farmwald** [whiskerz007/ubnt_get_wireguard#4] opened 2019-12-23 05:03 UTC
farmwald@RanchRouter:/config/scripts$ ./get_wireguard.sh
[INFO] Board type detected: e300
[INFO] Firmware version: v2.0.8.5247496.191120.1124
[INFO] Installed WireGuard version: 0.0.20191012-1
[INFO] Release version: 0.0.20191219-2
[INFO] Debian package URL: https://github.com/Lochnair/vyatta-wireguard/releases/download/0.0.20191219-2/wireguard-v2.0-e300-0.0.20191219-2.deb
Downloading WireGuard package...
Checking WireGuard package integrity...
Backing up running configuration...
Removing running WireGuard configuration...
RTNETLINK answers: File exists
[ERROR] 2@184 Unknown failure occured.

If you need more info, let me know.

**Comment by Metalnib** [comment] 2019-12-27 10:43
Can not reproduce!
I installed same version like yours 0.0.20191012-1 and then updated to latest 0.0.20191219-2  on mine ER-12(e300) without any issue! 

Did you migrate from version one of firmware?
What option do you have for ` route-allowed-ips` ? (I'm always on `false` and use PBR)

**Comment by whiskerz007** [comment] 2019-12-27 22:05
I've seen this problem when the running system configuration gets out of sync with the vyatta configuration system. Try to reboot the hardware and try the script again. Please report findings.

**Comment by farmwald** [comment] 2019-12-29 19:42
Still failing after fresh reboot.
log:

2019-12-29T11:39:16-0800: [INFO] Board type detected: e300
2019-12-29T11:39:16-0800: [INFO] Firmware version: v2.0.8.5247496.191120.1124
2019-12-29T11:39:16-0800: [INFO] Installed WireGuard version: 0.0.20191012-1
2019-12-29T11:39:18-0800: [INFO] Release version: 0.0.20191219-2
2019-12-29T11:39:19-0800: [INFO] Debian package URL: https://github.com/Lochnair/vyatta-wireguard/releases/download/0.0.20191219-2/wire
guard-v2.0-e300-0.0.20191219-2.deb
2019-12-29T11:39:19-0800: Downloading WireGuard package...
2019-12-29T11:39:20-0800: Checking WireGuard package integrity...
2019-12-29T11:39:20-0800: Backing up running configuration...
2019-12-29T11:39:20-0800: Removing running WireGuard configuration...
2019-12-29T11:39:21-0800: [ERROR] 2@184 Unknown failure occured.

Note that I have two wireguard interfaces, wg0 and wg1. I haven't looked at the code yet.

**Comment by whiskerz007** [comment] 2019-12-30 03:25
@farmwald That part of the code is used to mitigate IPv6 addresses being deleted with some changes to the running configuration. Can you verify if you have IPv6 addresses setup on either of your WireGuard interfaces?

**Comment by farmwald** [comment] 2019-12-30 03:33
No IPv6 addresses in the either config, only IPv4.

Mike



*From:* whiskerz007 [mailto:notifications@github.com]
*Sent:* Sunday, December 29, 2019 7:26 PM
*To:* whiskerz007/ubnt_get_wireguard
*Cc:* farmwald; Mention
*Subject:* Re: [whiskerz007/ubnt_get_wireguard] Fails on e300, works on
e1000 (#4)



@farmwald <https://github.com/farmwald> That part of the code is used to
mitigate IPv6 addresses being deleted with some changes to the running
configuration. Can you verify if you have IPv6 addresses setup on either of
your WireGuard interfaces?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/whiskerz007/ubnt_get_wireguard/issues/4?email_source=notifications&email_token=AJVLHUG273P46KT7NDV5Q4LQ3FS4DA5CNFSM4J6PV6NKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHZPT4Y#issuecomment-569571827>,
or unsubscribe

**Comment by Metalnib** [comment] 2019-12-30 03:35
Something similar happened to me too on UniFi Gateway, any change to wireguard configurations produce errors. It has nothing to do with this script, as whiskerz007 says it's vyatta being out of sync.

Here is how I fixed it:
1. backup your configuration commands. Remove WireGuard module: sudo modprobe --remove wireguard 
2. remove WG package: sudo dpkg --remove wireguard
3. Restart - your wireguard configuration will be clear at this step automatically.
4. Install wireguard and apply your configuration commands.

**Comment by whiskerz007** [comment] 2020-01-06 12:40
@farmwald Are you still having this issue? If you are, let me know if you have the ability to run this script on a factory reset device (after running one of the wizards to setup defaults).

**Comment by whiskerz007** [comment] 2020-01-30 06:34
Closing issue since no more concerns have been raised.

**Closed as completed by whiskerz007** 2020-01-30 06:34 UTC
