### ISSUE TITLE
Script installs same wireguard version every night

### ISSUE THREAD

**Issue by mxmartins** [whiskerz007/ubnt_get_wireguard#10] opened 2020-12-01 22:40 UTC
The get_wireguard.sh script runs (er8-xg) and sees version 1.0.20201112-3 as the most current version.  It also sees version 1.0.20201112-1 as the currently installed version.  Therefore, it downloads the -3 file and installs it.  That all works fine.
The problem is that the install package found in the -3 folder happens to install the -1 version.  I believe the issue is the mismatch of wireguard versions (-1) to the respective folder name (-3).
I ran it a few times to illustrate it...
Not sure there is an easy way to fix this, but wanted to bring it up to your attention.

2020-12-01T15:11:44-0700: [INFO] Board model: EdgeRouter Infinity
2020-12-01T15:11:44-0700: [INFO] Board type: e1000
2020-12-01T15:11:44-0700: [INFO] Board repo mapping: e1000
2020-12-01T15:11:44-0700: [INFO] Firmware version: v2.0.9.5346345.201028.1646
2020-12-01T15:11:44-0700: [INFO] Installed WireGuard version: 1.0.20201112-1
2020-12-01T15:11:45-0700: [INFO] Release version: 1.0.20201112-3
2020-12-01T15:11:45-0700: [INFO] Debian package URL: https://github.com/WireGuard/wireguard-vyatta-ubnt/releases/download/1.0.20201112-3/e1000-v2-v1.0.20201112-v1.0.20200827.deb
2020-12-01T15:11:45-0700: Downloading WireGuard package...
2020-12-01T15:11:46-0700: Checking WireGuard package integrity...
2020-12-01T15:11:46-0700: Backing up running configuration...
2020-12-01T15:11:47-0700: Removing running WireGuard configuration...
2020-12-01T15:11:50-0700: Removing WireGuard module...
2020-12-01T15:11:51-0700: Installing WireGuard...
2020-12-01T15:11:57-0700: Restoring previous running configuration...
2020-12-01T15:12:02-0700: Enabling WireGuard installation after firmware update...
2020-12-01T15:12:02-0700: WireGuard has been successfully installed.
2020-12-01T15:15:00-0700: [INFO] Board model: EdgeRouter Infinity
2020-12-01T15:15:00-0700: [INFO] Board type: e1000
2020-12-01T15:15:00-0700: [INFO] Board repo mapping: e1000
2020-12-01T15:15:00-0700: [INFO] Firmware version: v2.0.9.5346345.201028.1646
2020-12-01T15:15:00-0700: [INFO] Installed WireGuard version: 1.0.20201112-1
2020-12-01T15:15:01-0700: [INFO] Release version: 1.0.20201112-3
2020-12-01T15:15:01-0700: [INFO] Debian package URL: https://github.com/WireGuard/wireguard-vyatta-ubnt/releases/download/1.0.20201112-3/e1000-v2-v1.0.20201112-v1.0.20200827.deb
2020-12-01T15:15:01-0700: Downloading WireGuard package...
2020-12-01T15:15:02-0700: Checking WireGuard package integrity...
2020-12-01T15:15:02-0700: Backing up running configuration...
2020-12-01T15:15:02-0700: Removing running WireGuard configuration...
2020-12-01T15:15:06-0700: Removing WireGuard module...
2020-12-01T15:15:06-0700: Installing WireGuard...
2020-12-01T15:15:09-0700: Restoring previous running configuration...
2020-12-01T15:15:14-0700: Enabling WireGuard installation after firmware update...
2020-12-01T15:15:14-0700: WireGuard has been successfully installed.

**Comment by whiskerz007** [comment] 2020-12-02 00:39
Yes, this is caused by the latest release not properly configuring the DEB package. The next release should resolve this.

**Comment by whiskerz007** [comment] 2021-01-19 07:53
As of `1.0.20201221-1` this problem does not exist. Closing issue.

**Closed as completed by whiskerz007** 2021-01-19 07:53 UTC
